# Generated by Django 4.2.14 on 2024-11-23 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10)),
                ('vin', models.CharField(max_length=16)),
                ('year', models.CharField(max_length=4)),
                ('brand', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_number', models.CharField(max_length=24)),
                ('cost', models.FloatField(default=0)),
                ('premium', models.FloatField(default=0)),
                ('coverage_fire', models.BooleanField(default=False)),
                ('coverage_theft', models.BooleanField(default=False)),
                ('coverage_natural_disaster', models.BooleanField(default=False)),
                ('no_clame_discount', models.CharField(max_length=10)),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insured', to='insurance.car')),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policyholder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
