# Generated by Django 4.2.14 on 2024-11-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_car_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='insurance_number',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='premium',
        ),
    ]
