# Generated by Django 4.2.14 on 2024-11-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_remove_insurance_insurance_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='insured',
            new_name='insured_id',
        ),
    ]
