# Generated by Django 4.2.14 on 2024-11-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_rename_insured_insurance_insured_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='insured_id',
            new_name='insured',
        ),
    ]
