# Generated by Django 4.2.14 on 2024-11-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ID_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='driving_licence_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
