# Generated by Django 4.2.14 on 2024-12-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_of_upload',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
