# Generated by Django 4.2.14 on 2024-12-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_post_date_of_upload_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/insurance/images/'),
        ),
    ]
